[package]
name = "oodle"
repository = "https://github.com/sehnryr/oodle-rs"
description = "A Rust wrapper for the Oodle compression library (to be reimplemented)"
version = "0.1.0"
edition = "2024"
publish = false
keywords = ["oodle", "compression"]
categories = ["compression"]
exclude = ["/oodle-ue/", "/test-data/", "/.*", "/build.rs"]
include = ["/src/"]

[dependencies]
const_format = "0.2.34"
thiserror = "2.0.11"

[build-dependencies]
bindgen = "0.71.1"
cc = { version = "1.2.15", features = ["parallel"] }

[features]
default = []
simd = []
cold_path = []

[dev-dependencies]
criterion = "0.5.1"
oodle-sys = "0.2.0"

[[bench]]
name = "decompress"
harness = false

[profile.release]
opt-level = 3
strip = "symbols"
lto = true
panic = "abort"
codegen-units = 1
