[package]
name = "oodle"
repository = "https://github.com/sehnryr/oodle-rs"
description = "A reimplementation of the Oodle compression library"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false
keywords = ["oodle", "compression"]
categories = ["compression"]
exclude = ["/oodle-ue/", "/test-data/", "/.*", "/build.rs"]
include = ["/src/"]

[dependencies]
const_format = "0.2.34"
thiserror = "2.0.11"

[build-dependencies]
bindgen = "0.71.1"
cc = { version = "1.2.15", features = ["parallel"] }

[dev-dependencies]
criterion = "0.5.1"
oodle-sys = "0.2.0"

[[bench]]
name = "decompress"
harness = false
